name: Deploy Gaayong to Server

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'  # src 디렉토리 내 변경사항만 트리거
      - 'pom.xml' # pom.xml 변경도 트리거
      - '.github/workflows/deploy.yml' # deploy.yml 변경도 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # 리포지토리 코드 checkout - 로컬 검증용
    - name: Checkout
      uses: actions/checkout@v3

    # SSH 접속 및 배포 스크립트 실행
    - name: SSH Connection for Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }} 
        script: |
          cd /home/jini/gaayong
          ./script/deploy.sh