name: Deploy to Production

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'  # src 디렉토리 내 변경사항만 트리거
      - 'pom.xml' # pom.xml 변경도 트리거

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Display files
        run: ls -la target/

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "target/ROOT.war"
          target: "/tmp/"
          strip_components: 0

      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            find /tmp -name "*.war" -type f
            ls -la /tmp/
            cd /tmp
            /usr/bin/sh /home/jini/gaayong/script/deploy.sh