name: Deploy Gaayong to Server

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'  # src 디렉토리 내 변경사항만 트리거
      - 'pom.xml' # pom.xml 변경도 트리거
      - '.github/workflows/deploy.yml' # deploy.yml 변경도 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # 리포지토리 코드 checkout
    - name: Checkout
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
        git clone https://github.com/${{ github.repository }}.git
        cd $REPO_NAME
        git checkout ${{ github.ref_name }}

    # SSH 접속 및 배포 스크립트 실행
    - name: SSH Connection for Deploy
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PORT: ${{ secrets.PORT }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p $PORT $USERNAME@$HOST 'cd /home/jini/gaayong && ./script/deploy.sh'